/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Queue */
        get: operations["list_queue_api_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/artifact/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact Content */
        get: operations["artifact_content_api_approvals_artifact__artifact_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_approvals_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/pr/{pr_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pr Detail */
        get: operations["pr_detail_api_approvals_pr__pr_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/pr/{pr_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Pr */
        post: operations["merge_pr_api_approvals_pr__pr_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/question/{question_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Question */
        post: operations["answer_question_api_approvals_question__question_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_api_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backlog */
        get: operations["backlog_api_backlog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backlog/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder */
        post: operations["reorder_api_backlog_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/improvement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Improvement */
        get: operations["improvement_api_improvement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notes */
        get: operations["list_notes_api_notes_get"];
        put?: never;
        /** Create Note */
        post: operations["create_note_api_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prs */
        get: operations["list_prs_api_prs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Risks */
        get: operations["list_risks_api_risks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block */
        post: operations["block_api_tasks__task_id__block_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/greenlight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Greenlight */
        post: operations["greenlight_api_tasks__task_id__greenlight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unblock */
        post: operations["unblock_api_tasks__task_id__unblock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerRequest */
        AnswerRequest: {
            /** Answer */
            answer: string;
        };
        /**
         * ApprovalItem
         * @description One item in the ``awaiting_tyler`` queue. ``kind`` discriminates the
         *     backing entity; the SPA renders the matching detail view.
         */
        ApprovalItem: {
            /** Artifact Type */
            artifact_type?: string | null;
            /** Badge */
            badge: string;
            /** Blocking */
            blocking?: boolean | null;
            /** Github Pr */
            github_pr?: number | null;
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pr" | "artifact" | "decision" | "question";
            /** Project Id */
            project_id?: number | null;
            /** Risk Level */
            risk_level?: string | null;
            /** Title */
            title: string;
        };
        /** ApprovalsOut */
        ApprovalsOut: {
            /** Items */
            items: components["schemas"]["ApprovalItem"][];
        };
        /** ArtifactContentOut */
        ArtifactContentOut: {
            /** Content */
            content: string;
            /** Path */
            path: string;
            /** Truncated */
            truncated: boolean;
        };
        /** BacklogOut */
        BacklogOut: {
            /** Backlog */
            backlog: components["schemas"]["TaskOut"][];
            /** In Flight */
            in_flight: components["schemas"]["TaskOut"][];
            /** Planned */
            planned: components["schemas"]["TaskOut"][];
        };
        /** BlockRequest */
        BlockRequest: {
            /** Reason */
            reason: string;
        };
        /** CreateTaskRequest */
        CreateTaskRequest: {
            /** Depends On */
            depends_on?: number[];
            /** Prd Ref */
            prd_ref?: string | null;
            /** Project */
            project: number;
            /** Role */
            role?: string | null;
            /** Spec */
            spec?: string | null;
            /** Tier */
            tier?: ("plan" | "execute" | "local") | null;
            /** Title */
            title: string;
        };
        /** DebtOut */
        DebtOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence: string;
            /** Filed By */
            filed_by?: string | null;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Location */
            location: string;
            /** Passes Survived */
            passes_survived: number;
            /** Project Id */
            project_id?: number | null;
            /** Recurrence */
            recurrence: number;
            /** Resolved Ref */
            resolved_ref?: string | null;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pr" | "artifact" | "decision";
            /** Note */
            note?: string | null;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "approve" | "reject";
        };
        /** Finding */
        Finding: {
            /** Claim */
            claim?: string | null;
            /** Evidence */
            evidence?: string | null;
            /** Fix */
            fix?: string | null;
            /** Severity */
            severity?: string | null;
            /** Where */
            where?: string | null;
            /** Why */
            why?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImprovementOut */
        ImprovementOut: {
            /** Debt */
            debt: components["schemas"]["DebtOut"][];
            /** Learnings */
            learnings: components["schemas"]["LearningOut"][];
            /** Retros */
            retros: components["schemas"]["RetroOut"][];
        };
        /** LearningOut */
        LearningOut: {
            /** Category */
            category: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence?: string | null;
            /** Filed By */
            filed_by?: string | null;
            /** Id */
            id: number;
            /** Observation */
            observation: string;
            /** Retro Id */
            retro_id?: number | null;
            /** Status */
            status: string;
        };
        /** MergeOut */
        MergeOut: {
            /** Detail */
            detail: string;
            /** Merged */
            merged: boolean;
            /** Sha */
            sha?: string | null;
        };
        /** MessageOut */
        MessageOut: {
            /** Detail */
            detail: string;
        };
        /** NoteCreate */
        NoteCreate: {
            /** Body */
            body: string;
            /** Context */
            context?: string | null;
        };
        /** NoteOut */
        NoteOut: {
            /** Author */
            author?: string | null;
            /** Body */
            body: string;
            /** Context */
            context?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
        };
        /** PrDetailOut */
        PrDetailOut: {
            pr: components["schemas"]["PrOut"];
            /** Reviews */
            reviews: components["schemas"]["ReviewOut"][];
        };
        /** PrOut */
        PrOut: {
            /** Decided At */
            decided_at?: string | null;
            /** Em Summary */
            em_summary?: string | null;
            /** Github Pr */
            github_pr: number;
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Risk Level */
            risk_level?: string | null;
            /** Status */
            status: string;
            /** Task Id */
            task_id?: number | null;
            /** Tyler Decision */
            tyler_decision?: string | null;
        };
        /** QuestionOut */
        QuestionOut: {
            /** Answer */
            answer?: string | null;
            /** Answered At */
            answered_at?: string | null;
            /** Blocking */
            blocking: boolean;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Project Id */
            project_id?: number | null;
        };
        /** ReorderRequest */
        ReorderRequest: {
            /** Ordered Ids */
            ordered_ids: number[];
        };
        /** RetroOut */
        RetroOut: {
            /** Closed At */
            closed_at?: string | null;
            /** Doc Path */
            doc_path?: string | null;
            /** Id */
            id: number;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Trigger */
            trigger: string;
        };
        /** ReviewOut */
        ReviewOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Id */
            id: number;
            /** Model */
            model?: string | null;
            /** Pr Id */
            pr_id: number;
            /** Role */
            role: string;
            /** Strongest Objection */
            strongest_objection: string;
            /** Verdict */
            verdict: string;
        };
        /** RiskOut */
        RiskOut: {
            /** Acknowledged By */
            acknowledged_by?: string | null;
            /** Body */
            body?: string | null;
            /** Category */
            category: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decision Id */
            decision_id?: number | null;
            /** Id */
            id: number;
            /** Mitigation */
            mitigation?: string | null;
            /** Pr Id */
            pr_id?: number | null;
            /** Project Id */
            project_id: number;
            /** Resolved At */
            resolved_at?: string | null;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** RunOut */
        RunOut: {
            /** Cache Read Tokens */
            cache_read_tokens?: number | null;
            /** Cache Write Tokens */
            cache_write_tokens?: number | null;
            /** Cost Usd */
            cost_usd?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Id */
            id: number;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Log Ref */
            log_ref?: string | null;
            /** Mode */
            mode: string;
            /** Model */
            model: string;
            /** Outcome */
            outcome?: string | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Role */
            role: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Task Id */
            task_id?: number | null;
            /** Token Cost */
            token_cost?: number | null;
        };
        /** TaskOut */
        TaskOut: {
            /** Blocked */
            blocked: boolean;
            /** Blocked Reason */
            blocked_reason?: string | null;
            /** Branch */
            branch?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Depends On */
            depends_on: number[];
            /** Groom Rank */
            groom_rank?: number | null;
            /** Id */
            id: number;
            /** Model Tier */
            model_tier: string;
            /** Prd Ref */
            prd_ref?: string | null;
            /** Project Id */
            project_id: number;
            /** Role */
            role?: string | null;
            /** Spec */
            spec?: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_queue_api_approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalsOut"];
                };
            };
        };
    };
    artifact_content_api_approvals_artifact__artifact_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactContentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_approvals_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pr_detail_api_approvals_pr__pr_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pr_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_pr_api_approvals_pr__pr_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pr_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_question_api_approvals_question__question_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_api_auth_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    backlog_api_backlog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacklogOut"];
                };
            };
        };
    };
    reorder_api_backlog_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    improvement_api_improvement_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImprovementOut"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_notes_api_notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"][];
                };
            };
        };
    };
    create_note_api_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prs_api_prs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrOut"][];
                };
            };
        };
    };
    list_questions_api_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"][];
                };
            };
        };
    };
    list_risks_api_risks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskOut"][];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    block_api_tasks__task_id__block_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    greenlight_api_tasks__task_id__greenlight_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unblock_api_tasks__task_id__unblock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
